version: "2"

services:
    db:
        image: mongo
        expose:
            - "27017"
        volumes: 
            - mongodata:/data/db
    web:
        build: .
        depends_on:
            - db
        ports:
            - "8082:8082"
        volumes: 
            - /opt/app/node_modules
volumes: 
    mongodata: